#!/usr/bin/env sh
#
#
# wm independent hotkeys
#

## User space application launchers

# Bitwarden
super + b
	flatpak run com.bitwarden.desktop

# Browser Firefox
super + f
	firefox

# Thunar File Explorer
super + e
	thunar

# Terminal
super + Return
	kitty

# Wallpaper manager
super + ctrl + w
	nitrogen

## Termianl based applications

# Terminal based Text Editor / IDE nvim
ctrl + super + n
	kitty --detach --working-directory -e nvim $HOME/

# 2nd Terminal based Text Editor / IDE
ctrl + super + v
	kitty --detach --working-directory -e vim $HOME/

# program launcher
super + @space
	dmenu_run

# ranger file manager
super + ctrl + r
	kitty --detach --working-directory -e ranger

# make sxhkd reload its configuration files:
super + Escape
	pkill -USR1 -x sxhkd

# Edit bspwm config
super + ctrl + alt + 1
	kitty --detach --working-directory -e nvim /home/alan/.config/bspwm/bspwmrc

# Edit kitty config
super + ctrl + alt + 2 
	kitty --detach --working-directory -e nvim /home/alan/.config/kitty/kitty.conf

# Edit polybar config
super + ctrl + alt + 3
	kitty --detach --working-directory -e nvim /home/alan/.config/polybar/config.ini

# Edit sxhkd config
super + ctrl + alt + 4
	kitty --detach --working-directory -e nvim /home/alan/.config/sxhkd/sxhkdrc 

# Edit zsh config
super + ctrl + alt + 5
	kitty --detach --working-directory -e nvim /home/alan/.zshrc

#
# bspwm hotkeys
#

# quit/restart bspwm
super + alt + {q,r}
	bspc {quit,wm -r}

# close and kill
super + {_,shift + }w
	bspc node -{c,k}

# alternate between the tiled and monocle layout
super + m
	bspc desktop -l next

# send the newest marked node to the newest preselected node
super + y
	bspc node newest.marked.local -n newest.!automatic.local

# swap the current node and the biggest window
super + g
	bspc node -s biggest.window

#
# state/flags
#

# set the window state
super + {t,shift + t,s,f}
	bspc node -t {tiled,pseudo_tiled,floating,fullscreen}

# set the node flags
super + ctrl + {m,x,y,z}
	bspc node -g {marked,locked,sticky,private}

#
# focus/swap
#

# focus the node in the given direction
super + {_,shift + }{Left,Down,Up,Right}
	bspc node -{f,s} {west,south,north,east}

# focus the node for the given path jump
super + {p,b,comma,period}
	bspc node -f @{parent,brother,first,second}

# focus the next/previous window in the current desktop
super + {_,shift + }c
	bspc node -f {next,prev}.local.!hidden.window

# focus the next/previous desktop in the current monitor
super + bracket{left,right}
	bspc desktop -f {prev,next}.local

# focus the last node/desktop
super + {grave,Tab}
	bspc {node,desktop} -f last

# focus the older or newer node in the focus history
super + {o,i}
	bspc wm -h off; \
	bspc node {older,newer} -f; \
	bspc wm -h on

# focus or send to the given desktop
super + {_,shift + }{1-9,0}
	bspc {desktop -f,node -d} '^{1-9,10}'

#
# preselect
#

# preselect the direction
super + ctrl + alt + {Left,Down,Up,Right}
	bspc node -p {west,south,north,east}

# preselect the ratio
super + ctrl + {1-9}
	bspc node -o 0.{1-9}

# cancel the preselection for the focused node
super + ctrl + alt + space
	bspc node -p cancel

# cancel the preselection for the focused desktop
super + ctrl + shift + space
	bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel

#
# move/resize
#

# expand a window by moving one of its side outward
#super + alt + {h,j,k,l}
#	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# contract a window by moving one of its side inward
#super + alt + shift + {h,j,k,l}
#	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

# move a floating window
super + ctrl + {Left,Down,Up,Right}
	bspc node -v {-20 0,0 20,0 -20,20 0}


## Custom Resize
alt + super + {Left,Down,Up,Right}
	/home/alan/.config/bspmw/scripts/bspwm_resize {west,south,north,east}
