#! /bin/sh

## Export bspwm/bspwmrc dir to PATH
export PATH="${PATH}:$HOME/.config/bspwm"    #Implementar Var y escapar a Args

## Export sxhkd/sxhkdrc dir to path
export PATH="${PATH}:$HOME/.config/sxhkd"    #Implementar Var y escapar a Args

$HOME/.screenlayout/display.sh	&

$HOME/.config/polybar/launch.sh	&

bspc monitor -d I II III IV V VI VII VIII IX X

pgrep -x sxhkd > /dev/null || sxhkd	&

nitrogen --restore --set-zoom-fill	&
## feh --bg-fill /absolute/path/to/wallpaper &

picom -f &
#picom --experimental-back-end		&

# Cursor
xsetroot -cursor_name left_ptr		&

bspc config border_width         	1	
bspc config window_gap          	16
bspc config split_ratio          	0.50

# Border
bspc config focused_border_color        "#6c71c4"
bspc config normal_border_color         "#073642"
bspc config active_border_color         "#073642"


bspc config borderless_monocle     	true
bspc config gapless_monocle        	true
bspc config paddingless_monocle		true
bspc config single_monocle	   	false
bspc config focus_follows_pointer       true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
